name: dev
kind: Project
backend: gcs-backend
variables:
  organization: my-organization
  project: cdev-demo
  region: us-west1
  name: dev-test
  state_bucket_name: gke-demo-state
  state_bucket_prefix: dev
