name: cloud-storage
template: ./template/
kind: Stack
backend: gcs-backend
variables:
  name: {{ .project.variables.name }}
  region: {{ .project.variables.region }}
  location: {{ .project.variables.location }}
  project: {{ .project.variables.project }}
  content: |
    {{- readFile "./files/index.html" | nindent 4 }}
