{{- if .Values.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "huggingface-model.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "huggingface-model.labels" . | nindent 4 }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      pdbEnabled: {{ include "huggingface-model.fullname" . }}
{{- end }}
