apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-ui
  template:
    metadata:
      labels:
        app: chat-ui
    spec:
      containers:
      - name: chat-ui
        image: shalb/hf-chat-ui:v0.6
        env:
          - name: MONGODB_URL
            value: "mongodb://root:XoVBhCKiwo@mongodb/admin?directConnection=true&authSource=admin"
          - name: MODELS
            value: '[{"name": "TheBloke/Wizard-Vicuna-7B-Uncensored-AWQ", "endpoints": [{"url": "http://hfmodel-wizard-vicuna-7b-uncensored-awq:8080"}]}]'
            # value: '[{"name": "zephyr-7b-beta", "endpoints": [{"url": "http://hfmodel-zephyr-7b-beta"}], "parameters": {"temperature": 0.4, "top_p": 0.95, "repetition_penalty": 1.2, "top_k": 50, "truncate": 1000, "max_new_tokens": 1024} }]'
---
apiVersion: v1
kind: Service
metadata:
  name: chat-ui-service
spec:
  selector:
    app: chat-ui
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 3000