name: s3-website
template: ./template/
kind: Stack
backend: aws-backend
variables:
  bucket_name: "tmpl-dev-test"
  region: {{ .project.variables.region }}
  content: |
    {{- readFile "./files/index.html" | nindent 4 }}
