name: cdev-tests-local
template: ./template/
kind: Stack
backend: aws-backend
variables:
  bucket_name: "tmpl-dev-test"
  region: {{ .project.variables.region }}
  organization: {{ .project.variables.organization }}
  name: "Developer"
  index_content: |
    {{- readFile "./files/index.html" | nindent 4 }}
